### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by grit96** [itsapi/github-listener#19]
Add documentation to readme on:

- [x] Travis and GitHub support
- [x] adding webhooks in Travis and GitHub
- [x] how to install and run
- [x] how to contribute

**Comment by olls** [comment]
Issues can be left open

**Comment by grit96** [comment]
They can if they need to. Why does this need to?

**Comment by olls** [comment]
The checklist is not finished

**Comment by grit96** [comment]
Because I don't think the last one is necessary

**Comment by grit96** [comment]
Do you think it's something we need to add?

**Comment by olls** [comment]
I don't know.

**Comment by grit96** [comment]
2f5824e90dc4314693a15cccc514bff631211b00
