### ISSUE TITLE
Better npm support

### ISSUE THREAD

**Issue by grit96** [itsapi/github-listener#23]
At the moment the module doesn't really benefit from being on npm.
A few ways we could improve it:

- [x] modularise `server.js` so people can use it programmatically
- [x] add a binary wrapper for `server.js` so it can be installed globally and run as a command
- [x] add api docs

**Comment by olls** [comment]
Related to this the `readme` formatting needs fixing for NPM and the installation instructions should mention NPM.

**Comment by grit96** [comment]
Updated `README.md` with fixed headings and npm mention.
