### ISSUE TITLE
Perhaps escape ANSI colour codes in script out

### ISSUE THREAD

**Issue by grit96** [itsapi/github-listener#26]
Migrated from itsapi/post-receive#13

Otherwise we may see escape characters in the HTML output.

**Comment by olls** [comment]
We should implement a function to convert the ANSI escape colour codes to spans with colours.

**Comment by grit96** [comment]
:+1:

**Comment by grit96** [comment]
https://github.com/rburns/ansi-to-html

**Comment by grit96** [comment]
6c6ac93376f80fd3bc74ee5a83f4ccdb7c73d404
