### ISSUE TITLE
jshint

### ISSUE THREAD

**Issue by grit96** [itsapi/github-listener#33]
- [x] Add curly brackets to `if/else` statements
- [x] `===` instead of `==`
- [x] Add rules to `.jshintrc`

**Comment by grit96** [comment]
Are there any other jshint [options](http://jshint.com/docs/options/) we should add (e.g. `undef` and `unused`)?

**Comment by olls** [comment]
Yes to both, what about [`maxcomplexity`](http://jshint.com/docs/options/#maxcomplexity)

**Comment by grit96** [comment]
We need to fix complex functions:
```
listener.js: line 46, col 38, This function's cyclomatic complexity is too high. (7)

server.js: line 103, col 35, This function's cyclomatic complexity is too high. (7)

2 errors
```

**Comment by grit96** [comment]
Need @olls to finish modifications on `listener.js` before we can reduce complexity on `listener.hook`.
